services:
  associates:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: associates_app
    image: associates:v-1.0
    ports:
      - "8050:8050"
    depends_on:
      - db_associates
      - redis_cache
    environment:
      DATABASE_URL: postgresql://${USERSERVER}:${PASSWORD}@db:${PORT}/${DATABASE}
      TZ: America/Sao_Paulo
    env_file:
      - .env
    # volumes:
    #   - ./data:/app/data
  
  db_associates:
    image: postgres:latest
    container_name: db_associates
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USERSERVER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - associates_db_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USERSERVER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:7
    container_name: redis_cache
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"


volumes:
  associates_db_2:
